In [ ]:
"""Daniel Novikov
01/24/2022
"""

In [13]:
'''
1. Fill a 7x7 ndarray with random values from 0-6
'''
import numpy as np

# Create random matrix whos values are in half-open interval [0,1)
A = np.random.random(size=(7,7))

# Scale matrix to [0,6)
A = A * 6

In [14]:
A

array([[1.66279879, 3.4467793 , 3.02615031, 5.24405768, 5.75042026,
        2.38288046, 4.41486161],
       [3.75701251, 2.79088303, 0.57411969, 2.40618275, 5.01024484,
        5.40991078, 3.11044261],
       [4.82898829, 1.84837744, 1.62750103, 5.14826048, 1.60106611,
        1.09430518, 1.53090274],
       [4.42029881, 2.21162304, 2.40180053, 5.893175  , 1.7428154 ,
        4.8308312 , 1.60493761],
       [2.29731443, 2.67837472, 2.54920944, 1.83536508, 3.30366842,
        0.52034668, 1.5122764 ],
       [1.68711733, 3.17387378, 3.37045707, 2.16985308, 4.96656714,
        5.82903309, 5.48269412],
       [5.45209529, 1.13629273, 3.14860238, 2.57685948, 3.07941636,
        3.01329224, 5.10984569]])

In [15]:
type(A)

numpy.ndarray

In [55]:
'''
2. Write a program that takes takes a n-vector and creates a matrix,
whos rows consist of a sliding window of 3 adjacent components in the vector.
The window starts at the beginning of the vector, slides over one cell at a time,
and stops when the last variable of the window reaches the end of the vector.

'''

n = 10
A = np.random.random(n) * 7
A = A.astype(int)

def solve(A):
    if len(A) < 3: return A
    result = np.ndarray(shape=(0,3))
    for x in range(len(A)-2):
        result = np.vstack([result, (A[x], A[x+1], A[x+2])])
    return result

print(A)
solve(A)


[0 5 6 3 4 2 3 4 1 6]


array([[0., 5., 6.],
       [5., 6., 3.],
       [6., 3., 4.],
       [3., 4., 2.],
       [4., 2., 3.],
       [2., 3., 4.],
       [3., 4., 1.],
       [4., 1., 6.]])

In [ ]:
'''3. How can we save time using stochastic gradient compared to standard gradient descent? Do we have a better method? '''

'''
Standard gradient descent (GD) calculates error on the entire dataset after each learning step.
Stochastic gradient descent (SGD) calculates error on each incoming datapoint one at a time, taking a learning step each time.

Thus SGD takes learning steps more often than GD. And after each learning step, the choice of parameters get less wrong.

We expect to converge onto local minima faster with SGD as we take many learning steps quickly.

It is more likely that SGD will find a solution after a single pass through the data;
unlike GD, which makes an entire pass through the data with each learning step.

A better method seems to be batch gradient desccent, which takes learning steps on subsets of data. 
This combines the speed of SGD with the learning step quality that multiple  datapoints on each update step.

Also, adding a momemntum term can help us converge faster and be more resilient to noise.

'''