In [ ]:
#Given an i-vector "y" and 0 <= j <= 50
#Broadcast y over j columns to create ixj matrix "X"

In [1]:
import numpy as np

In [8]:
y = np.arange(-20, 20, 0.1)
X = np.zeros((len(y), 50))

In [18]:
y.shape

(400,)

In [19]:
y=y.reshape(len(y), 1)

In [20]:
y.shape

(400, 1)

In [10]:
X.shape

(400, 50)

In [11]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
#Solution:
X + y

array([[-20. , -20. , -20. , ..., -20. , -20. , -20. ],
       [-19.9, -19.9, -19.9, ..., -19.9, -19.9, -19.9],
       [-19.8, -19.8, -19.8, ..., -19.8, -19.8, -19.8],
       ...,
       [ 19.7,  19.7,  19.7, ...,  19.7,  19.7,  19.7],
       [ 19.8,  19.8,  19.8, ...,  19.8,  19.8,  19.8],
       [ 19.9,  19.9,  19.9, ...,  19.9,  19.9,  19.9]])

In [22]:
X.T + y.T

array([[-20. , -19.9, -19.8, ...,  19.7,  19.8,  19.9],
       [-20. , -19.9, -19.8, ...,  19.7,  19.8,  19.9],
       [-20. , -19.9, -19.8, ...,  19.7,  19.8,  19.9],
       ...,
       [-20. , -19.9, -19.8, ...,  19.7,  19.8,  19.9],
       [-20. , -19.9, -19.8, ...,  19.7,  19.8,  19.9],
       [-20. , -19.9, -19.8, ...,  19.7,  19.8,  19.9]])